# Generated by Django 4.1.2 on 2022-10-22 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name="UserInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32)),
                ("password", models.CharField(max_length=64)),
                ("age", models.IntegerField()),
                (
                    "account",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("create_time", models.DateTimeField(default=1992)),
                (
                    "gender",
                    models.SmallIntegerField(choices=[(1, "男"), (2, "女")], default=1),
                ),
                (
                    "department",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app01.department",
                    ),
                ),
            ],
        ),
    ]
