# Generated by Django 4.1.2 on 2022-10-25 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0003_prettynum"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prettynum",
            name="level",
            field=models.SmallIntegerField(
                choices=[(1, "1级"), (2, "2级"), (3, "3级"), (4, "4级"), (5, "5级")],
                default=1,
                verbose_name="等级",
            ),
        ),
        migrations.AlterField(
            model_name="prettynum",
            name="status",
            field=models.SmallIntegerField(
                choices=[(1, "未使用"), (2, "已使用")], default=1, verbose_name="状态"
            ),
        ),
    ]
