# Generated by Django 4.1.2 on 2022-10-27 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0004_alter_prettynum_level_alter_prettynum_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="Admin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=32, verbose_name="用户名")),
                ("password", models.CharField(max_length=64, verbose_name="密码")),
            ],
        ),
    ]
